### ISSUE TITLE
Add CSV Reader.

### ISSUE THREAD

**Issue by joaoluisro** [joaoluisro/Quebra-de-Barreira---BCC#2]
Implement a CSV class and ways to manipulate the data.

cf @almeidaraul

**Comment by almeidaraul** [comment]
Please be more specific

**Comment by joaoluisro** [comment]
> Please be more specific

I think i've made it pretty clear.

**Comment by almeidaraul** [comment]
> > Please be more specific
> 
> I think i've made it pretty clear.

I deeply disagree.
